//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.CategoryDescriptions = new HashSet<CategoryDescription>();
            this.Characteristics = new HashSet<Characteristic>();
            this.Descriptions = new HashSet<Description>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsItDefault { get; set; }
    
        public virtual ICollection<CategoryDescription> CategoryDescriptions { get; set; }
        public virtual ICollection<Characteristic> Characteristics { get; set; }
        public virtual ICollection<Description> Descriptions { get; set; }
    }
}
