//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CharacteristicValues = new HashSet<CharacteristicValue>();
            this.Colors = new HashSet<Color>();
            this.Descriptions = new HashSet<Description>();
            this.Photos = new HashSet<Photo>();
            this.Prices = new HashSet<Price>();
            this.ProductOrders = new HashSet<ProductOrder>();
            this.Sizes = new HashSet<Size>();
            this.Discounts = new HashSet<Discount>();
            this.Categories = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CharacteristicValue> CharacteristicValues { get; set; }
        public virtual ICollection<Color> Colors { get; set; }
        public virtual ICollection<Description> Descriptions { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
        public virtual ICollection<Size> Sizes { get; set; }
        public virtual ICollection<Discount> Discounts { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}
